package com.connectycube.flutter.connectycube_flutter_call_kit

const val EXTRA_CALL_ID = "extra_call_id"
const val EXTRA_CALL_TYPE = "extra_call_type"
const val EXTRA_CALL_INITIATOR_ID = "extra_call_initiator_id"
const val EXTRA_CALL_INITIATOR_NAME = "extra_call_initiator_name"
const val EXTRA_CALL_OPPONENTS = "extra_call_opponents"
const val EXTRA_CALL_USER_INFO = "extra_call_user_info"
const val EXTRA_PUSH_TOKEN = "extra_push_token"
const val EXTRA_CALL_PHOTO = "photo_url"
const val EXTRA_ACCEPT_BUTTON_LABEL = "accept_button_label"
const val EXTRA_REJECT_BUTTON_LABEL = "reject_button_label"
const val EXTRA_CALL_DURATION = "extra_call_duration"
const val EXTRA_BACKGROUND_COLOR = "extra_background_color"
const val EXTRA_BACKGROUND_URL = "extra_background_url"
const val EXTRA_LOGO_URL = "extra_logo_url"
const val EXTRA_IS_SHOW_LOGO = "extra_is_show_logo"
const val EXTRA_TEXT_COLOR = "extra_text_color"
const val EXTRA_ACTION_COLOR = "extra_action_color"
const val EXTRA_RINGTONE_PATH = "extra_ringtone_path"
const val EXTRA_MISSED_SHOW = "extra_missed_show"
const val EXTRA_MISSED_SUBTITLE = "extra_missed_subtitle"
const val EXTRA_MISSED_CALLBACK_TEXT = "extra_missed_callback_text"
const val EXTRA_MISSED_SHOW_CALLBACK = "extra_missed_show_callback"
const val EXTRA_MISSED_COUNT = "extra_missed_count"
const val EXTRA_MISSED_ID = "extra_missed_id"
const val EXTRA_MISSED_CHANNEL_NAME = "extra_missed_channel_name"

const val ACTION_CALL_ACCEPT = "action_call_accept"
const val ACTION_CALL_REJECT = "action_call_reject"
const val ACTION_CALL_INCOMING = "action_call_incoming"
const val ACTION_CALL_NOTIFICATION_CANCELED = "action_call_notification_canceled"
const val ACTION_CALL_ENDED = "action_call_ended"
const val ACTION_CALL_TIMEOUT = "action_call_timeout"
const val ACTION_CALL_CALLBACK = "action_call_callback"
const val ACTION_TOKEN_REFRESHED = "action_token_refreshed"

const val REJECTED_IN_BACKGROUND = "rejected_in_background"
const val ACCEPTED_IN_BACKGROUND = "accepted_in_background"
const val INCOMING_IN_BACKGROUND = "incoming_in_background"
const val MISSED_CALLBACK_IN_BACKGROUND = "missed_callback_in_background"

const val CALL_TYPE_PLACEHOLDER = "Incoming %s call"

const val CALL_STATE_PENDING: String = "pending"
const val CALL_STATE_ACCEPTED: String = "accepted"
const val CALL_STATE_REJECTED: String = "rejected"
const val CALL_STATE_UNKNOWN: String = "unknown"

const val DEFAULT_CALL_DURATION_MS: Long = 60000L
